Fixed build error in the Python code
gcc-14 is more anal, and we need to be more accepting of some stuff inside
Python. Prior to this patch I would see this in gcc-14:

  /usr/include/python3.12/object.h:142:9: error: initialization of 'long int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]